//! The flow goldens (contracts/fixtures/flow/golden.ndjson, plan v2.31
//! step 4 A3): the first five request lines are real source through the
//! lowering — each snippet below, `lower_file`, its first unit alone
//! through `wire::body` — and every reply line is the core's answer
//! (fixture_contract::regen). The sixth pair, the tree-shape refusal, is
//! a hand-written illegal request no lowering produces; the regenerator
//! keeps it as filed. They are regenerated by two ignored legs in order,
//! both under CE_BLESS=1: `flow_golden::regen` rewrites the five request
//! lines from the snippets, then `fixture_contract::regen` re-answers
//! every reply. The replies are read for what the snippets hold as well.

use codeeraser::flow::lower::lower_file;
use codeeraser::flow::wire::{self, Sent};
use codeeraser::scan::lang::Lang;
use serde_json::Value;
use std::path::Path;

const REL: &str = "flow/golden.ndjson";

/// The requests' proto: the major's floor, as every family's request
/// line carries it (query_golden.rs::REQUEST_PROTO).
const REQUEST_PROTO: &str = crate::facts::ver::ANCHOR;

/// `==== <ext> <id> <kinds the core finds>` over each snippet.
const SNIPPETS: &str = "\
==== py 1 unreachable
def f(a):
    if a:
        x = 1
    else:
        x = 2
    return x
    print(x)
==== ts 2 dead_store
function f(): number {
    let x = 1;
    x = 2;
    return x;
}
==== go 3 unused_local
func f() int {
    x := 1
    x = 2
    return 0
}
==== java 4 unused_param
int f(int a, int b) {
    return a;
}
==== java 5 unreachable dead_store
int f() {
    int x;
    try {
        x = 1;
        return 0;
    } finally {
        done();
    }
    return x;
}
";

const KINDS: [&str; 4] = ["unreachable", "dead_store", "unused_local", "unused_param"];

/// (id, extension, the kinds the reply holds, source).
fn snippets() -> Vec<(usize, &'static str, Vec<&'static str>, &'static str)> {
    SNIPPETS
        .split("==== ")
        .filter(|b| !b.is_empty())
        .map(|b| {
            let (head, text) = b.split_once('\n').expect("a snippet header");
            let mut words = head.split(' ');
            let ext = words.next().expect("an extension");
            let id = words.next().and_then(|w| w.parse().ok()).expect("an id");
            (id, ext, words.collect(), text)
        })
        .collect()
}

/// A snippet's request line: its first unit alone, lowered and on the
/// wire, the envelope written in the goldens' field order.
fn request(id: usize, ext: &str, text: &str) -> String {
    let lang = Lang::from_path(Path::new(&format!("x.{ext}"))).expect("a known extension");
    let mut lowered = lower_file(text, lang).expect("a flow language");
    assert!(lowered.unlowered.is_empty(), "snippet {id} lowers");
    lowered.units.truncate(1);
    let files = [lowered];
    let sent = Sent {
        files: &files,
        units: vec![(&files[0].units[0], 0)],
    };
    let body = wire::body(&sent);
    format!(
        "{{\"proto\":\"{REQUEST_PROTO}\",\"type\":\"flow.request\",\"id\":{id},\"units\":{},\"stmts\":{},\"vars\":{},\"uses\":{}}}",
        body["units"], body["stmts"], body["vars"], body["uses"]
    )
}

fn regenerated() -> Vec<String> {
    snippets()
        .iter()
        .map(|(id, ext, _, text)| request(*id, ext, text))
        .collect()
}

fn filed() -> Vec<(String, String)> {
    crate::fixture_contract::golden_pairs(REL)
}

#[test]
fn the_first_five_request_lines_are_the_snippets_through_the_lowering() {
    crate::fixture_contract::assert_generated(REL, &regenerated(), 1, "flow_golden");
}

/// Request lines rewritten from the snippets, the refusal pair after
/// them as filed; a reply line kept where one is filed — the core's
/// regenerator (fixture_contract::regen) answers them next.
#[test]
#[ignore]
fn regen() {
    crate::fixture_contract::rewrite_generated(REL, &regenerated(), 1);
}

/// Each reply holds exactly the kinds its snippet's header names, and
/// the sixth is the shape refusal.
#[test]
fn the_replies_find_what_the_snippets_hold() {
    let pairs = filed();
    for ((id, _, kinds, _), (_, reply)) in snippets().iter().zip(&pairs) {
        let reply: Value = serde_json::from_str(reply).expect("a reply line");
        let rows = reply["findings"].as_array().expect("findings");
        let found: Vec<&str> = rows
            .iter()
            .map(|r| KINDS[r[1].as_u64().expect("a kind") as usize])
            .collect();
        assert_eq!(&found, kinds, "pair {id}: {reply}");
    }
    let last: Value = serde_json::from_str(&pairs[5].1).expect("a reply line");
    assert_eq!(
        last["message"],
        "stmt 0: if branches disagree with has_else"
    );
}
