//! The query goldens (contracts/fixtures/query/golden.ndjson, plan
//! v2.31 step 2) are the lexer's own output: every request line is the
//! built-in prelude followed by one of the programs below, lexed by
//! cli/src/query/lexer.rs over the same six fact tables, and every
//! reply line is the core's answer (fixture_contract::regen). They are
//! regenerated by two ignored legs in order, both under CE_BLESS=1:
//! `query_golden::regen` rewrites the request lines from the programs,
//! then `fixture_contract::regen` re-answers every reply. Without the
//! bless each dry run fails naming what moved. The replies are read
//! for what the programs MEAN as well — the goldens are a contract of
//! the core's behaviour on the prelude, not only a byte replay.

use codeeraser::query::{PRELUDE, legend, program::Program};
use serde_json::{Value, json};

const REL: &str = "query/golden.ndjson";

/// The requests' proto: the major's floor, as every family's request
/// line carries it (the server answers the current one; the 7.2.0
/// regenerator minted its new scan and graph requests the same way).
const REQUEST_PROTO: &str = "7.0.0";

/// `id [why] [schema]` on a block's first line, the program under it;
/// each block lexes after the prelude as the request's rules source.
const PROGRAMS: &str = "\
1 schema
====
2
assert no_dead(F) :- dead(F).
====
3 why
?- depends(A, B), not same_dir(A, B).
====
4
?- file(F), F = .
====
5
?- file(F), G != F.
====
6
odd(F) :- file(F), not even(F).
even(F) :- file(F), not odd(F).
?- odd(F).
====
7
?- lines(F, N), M = N * 2 + 1, M > 20.
====
8
?- N = count(F : in(F, \"src/**\")).
";

/// Four files in two directories, one named entry, a chain of two
/// imports (file 3 unreached), their line counts, and one set.
fn facts() -> Value {
    let (entry, import) = (legend::sym("entry_named"), legend::sym("import"));
    json!({
        "1": [[0], [1], [2], [3]],
        "2": [[0, 0], [1, 0], [2, 1], [3, 1]],
        "7": [[0, entry]],
        "8": [[0, 3], [1, 9], [2, 12], [3, 40]],
        "9": [[0, 1, import, 1], [1, 2, import, 1]],
        "26": [[0, 0], [0, 1]],
    })
}

fn blocks() -> Vec<(usize, Vec<&'static str>, &'static str)> {
    PROGRAMS
        .split("====\n")
        .map(|b| {
            let (head, text) = b.split_once('\n').expect("a block header");
            let mut words = head.split(' ');
            let id: usize = words.next().and_then(|w| w.parse().ok()).expect("an id");
            (id, words.collect(), text)
        })
        .collect()
}

fn request(id: usize, flags: &[&str], text: &str) -> String {
    let p = Program::lex(PRELUDE, Some(text), None).expect("the program lexes");
    let mut line = format!(
        "{{\"proto\":\"{REQUEST_PROTO}\",\"type\":\"query.request\",\"id\":{id},\"program\":{},\"facts\":{},\"prelude\":{}",
        Value::Array(p.wire()),
        facts(),
        p.prelude_clauses
    );
    for flag in flags {
        line.push_str(&format!(",\"{flag}\":true"));
    }
    line.push('}');
    line
}

fn regenerated() -> Vec<String> {
    blocks()
        .iter()
        .map(|(id, flags, text)| request(*id, flags, text))
        .collect()
}

fn filed() -> Vec<(String, String)> {
    crate::fixture_contract::golden_pairs(REL)
}

fn reply(id: usize) -> Value {
    let pairs = filed();
    let (_, r) = &pairs[id - 1];
    serde_json::from_str(r).expect("a reply line")
}

#[test]
fn every_request_line_is_the_prelude_then_its_program_through_the_lexer() {
    crate::fixture_contract::assert_generated(REL, &regenerated(), 0, "query_golden");
    let prelude = Program::lex(PRELUDE, None, None).expect("the prelude lexes");
    for (req, _) in &filed() {
        let d: Value = serde_json::from_str(req).expect("a request line");
        let tokens = d["program"].as_array().expect("tokens");
        assert_eq!(d["prelude"], prelude.prelude_clauses);
        assert_eq!(tokens[..prelude.tokens.len()], prelude.wire()[..]);
    }
}

/// Request lines rewritten from the programs; a reply line kept
/// where one is filed, `{}` where a program is new — the core's
/// regenerator (fixture_contract::regen) answers them next.
#[test]
#[ignore]
fn regen() {
    crate::fixture_contract::rewrite_generated(REL, &regenerated(), 0);
}

/// What the eight programs mean, read off the filed replies.
#[test]
fn the_replies_say_what_the_programs_mean() {
    let n = Program::lex(PRELUDE, None, None).unwrap().tokens.len() as i64;
    // 1: the schema echo is this side's legend, row for row
    assert_eq!(reply(1)["schema"], json!(legend::schema_rows()));
    // 2: the assertion holds one violation — the unreached file 3
    let two = reply(2);
    assert_eq!(
        (&two["goals"], &two["answers"]),
        (&json!([[0, 1, 0]]), &json!([[0, 3]]))
    );
    assert_eq!(two["counts"]["violations"], 1);
    // preds lists the rule-defined predicates: the prelude's six, never the assertion's head
    let prelude_preds = json!([
        [1000, 0],
        [1001, 0],
        [1002, 0],
        [1003, 0, 0],
        [1004, 0, 0],
        [1005, 1, 1]
    ]);
    assert_eq!(two["preds"], prelude_preds);
    assert!(
        !two["proof"].as_array().unwrap().is_empty(),
        "a violation carries its derivation"
    );
    // 3: two cross-directory dependencies, each with a proof under why
    let three = reply(3);
    assert_eq!(three["answers"], json!([[0, 0, 2], [0, 1, 2]]));
    assert!(three["counts"]["proofNodes"].as_u64().unwrap() > 0);
    // 4 / 5 / 6: the three error codes at their tokens
    assert_eq!(reply(4)["errors"], json!([[n + 8, 1]]));
    assert_eq!(reply(5)["errors"], json!([[n + 6, 5]]));
    assert_eq!(reply(6)["errors"], json!([[n, 6]]));
    // 7: arithmetic and a comparison over the line counts
    let seven: Vec<Value> = reply(7)["answers"].as_array().unwrap().clone();
    assert_eq!(seven.len(), 2);
    assert!(seven.contains(&json!([0, 2, 12, 25])) && seven.contains(&json!([0, 3, 40, 81])));
    // 8: the set sugar under an aggregate
    assert_eq!(reply(8)["answers"], json!([[0, 2]]));
}
